### ISSUE TITLE
Support custom traits

### ISSUE THREAD

**Issue by gonzojive** [rmrobinson/google-smart-home-action-go#6]
The README indicates there's support for custom traits, but `Device`'s `attribute` field is private, and I don't see a way to mutate it with function calls. My conclusion is custom trait support is intended, but it's not possible to add traits that require setting additional attributes.

Language from `README.md`

> This library has wrappers for some of the most common types of devices and traits to simplify the process of creating a representation of your actual device logic within the home graph. In order to provide flexibility for the consumer of the library, however, it also allows for manual definition of Devices and Traits that can be returned by any API call.

To support custom traits, I suppose some options are...

1. Make `Device.attributes` public.
2. Add some other sort of API, like

```go
func (d *Device) AddCustomTrait(t Trait) *Device {
  setAttribute := func(key string, val any) { d.attributes[key] = val }
  t.ApplyToDevice(d, setAttribute)
  return d
}
```

**Comment by gonzojive** [comment]
Also thanks for this library!

**Comment by gonzojive** [comment]
This is regarding https://github.com/gonzojive/heatpump/issues/5, where I need support for a thermostat type device.

**Comment by zopieux** [comment]
I needed this for my own project. Instead of adding more API surface like you suggest, I went and suggested #9 which simply makes the (very simple) internal state public for the user to override, both `State` and `Attributes`.

I believe this is a reasonable approach. This library can't play cat & mouse with Google every time they add some traits or device types.

**Comment by rmrobinson** [comment]
Thank you for the report @gonzojive  and thank you for the fix @zopieux . I'm going to go ahead and close this issue since it seems like it has been solved.
